### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by firminochangani** [kiandahub/kiandahub.github.io#1]
Create an english version of the Landing Page ASAP.

**Comment by dizandonorton** [comment]
Estás a utilizar alguma frameword? Alguma permitem activar a internacionalização num instante.

**Comment by JoseCage** [comment]
@flowck  Outra opção seria criar um ficheiro de configuração em **.yml** se for o caso de estares a trabalhar com PHP. Exemplo: Dentro de languages/en-us.yml;

`
"Subscreva": "Subscribe"
`

 Por ai vai. E no php usas algumas funções para passar esses dados quando for escolhido determinada língua. Ou mesmo, invés do yaml usas o próprio php. O @valdiney já usou tradução de texto em algum dos seus projetos, talvez possa dar uma luz.

**Comment by firminochangani** [comment]
@JoseCage Nesse momento estamos a usar o Wordpress juntamente com o Polylang para a gestão dos idiomas e Poedit para a tradução das strings do site e para a gerar os ficheiros de tradução.

**Comment by JoseCage** [comment]
Opa.. Certo @flowck ..
Até mais então.
